version: '3'
services:
  findmymasters-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findmymasters-api
    restart: always
    ports:
      - 3000:3000
    env_file:
      - env/production.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
