version: '3'
services:
  findmymasters-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: findmymasters-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - env/local.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-tier
