version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgresprismadb
    restart: always
    environment:
      POSTGRES_DB: findmymastersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '15432:5432'
    env_file:
      - env/production.env
    volumes:
      - postgres:/var/lib/postgressql/data
    networks:
      - app-tier

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - app-tier

  findmymasters-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findmymasters-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - env/production.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-tier

volumes:
  postgres:
    name: nest-prisma-docker-db
  pgadmin:

networks:
  app-tier:
    driver: bridge
