version: '3'
services:
  deployment-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
      - 5432:5432
    env_file:
      - env/local.env
    volumes:
      - .:/app
      - /app/node_modules
