version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgresprismadb
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    env_file:
      - env/local.env
    volumes:
      - postgres:/var/lib/postgressql/data

  findmymasters-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: findmymasters-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - env/local.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-tier

volumes:
  postgres:
    name: nest-prisma-docker-db

networks:
  app-tier:
    driver: bridge
