version: '3'
services:
  findmymasters-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findmymasters-api
    restart: always
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - 3000:8081
    env_file:
      - env/production.env
    volumes:
      - .:/app
      - /app/node_modules
