/*
  Warnings:

  - The values [JOURNALISMANDMASSCOMMUNICATION,ENVIRONMENT,TOURISMANDHOSTITALITY,FOODANDBEVERAGE] on the enum `Field` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Field_new" AS ENUM ('ADMINISTRATION', 'ARCHITECTURE', 'ART', 'AVIATION', 'BUSINESS', 'CONSTRUCTION', 'COSMETOLOGY', 'DESIGN', 'ECONOMIC', 'EDUCATION', 'ENERGY', 'ENGINEERING', 'ENVIRONMENTAL', 'FASHION', 'FOOD_AND_BEVERAGE', 'GENERAL', 'HEALTHCARE', 'HUMANITIES', 'JOURNALISM_AND_MASSCOMMUNICATION', 'LANGUAGES', 'LAW', 'LIFE', 'LIFESKILLS', 'MANAGEMENT', 'MARKETING', 'NATURAL', 'PERFORMINGARTS', 'PROFESSIONAL', 'SELFIMPROVEMENT', 'SOCIAL', 'SPORT', 'SUSTAINABILITY', 'TECHNOLOGY', 'TOURISM_AND_HOSPITALITY');
ALTER TABLE "master-program" ALTER COLUMN "field" TYPE "Field_new" USING ("field"::text::"Field_new");
ALTER TYPE "Field" RENAME TO "Field_old";
ALTER TYPE "Field_new" RENAME TO "Field";
DROP TYPE "Field_old";
COMMIT;
